language: node_js
node_js:
  - "lts/*"
notifications:
  email: false

stages:
  - name: lint
  - name: test
  - name: publish
    if: tag IS present
  - name: docs
    if: branch = master AND type != pull_request

jobs:
  include:
    - name: "Check Linting"
      stage: lint
      os: linux
      script: npm run lint
    - name: "Test on Linux"
      stage: test
      os: linux
      services:
        - xvfb
      before_script:
        - export DISPLAY=:99.0
      script: npm test
    - name: "Test on OSX"
      stage: test
      os: osx
      script: npm test
    # Enable when Spectron tests are fixed on Travis Windows Jobs:
    # https://travis-ci.community/t/spectron-integration-test-failing-on-travis/6762
    # - name: "Test on Windows"
    #   stage: test
    #   os: windows
    #   script: npm test
    - name: "Publish from Linux"
      stage: publish
      os: linux
      script: npm run publish
    - name: "Publish from OSX"
      stage: publish
      os: osx
      script: npm install --save-dev macos-alias && npm run publish
    - name: "Publish from Windows"
      stage: publish
      os: windows
      script: npm run publish
    - name: "Regenerate Documentation"
      stage: docs
      os: linux
      script: sh ./.travis/deployDocs.sh
