language: node_js
node_js:
  - "lts/*"
notifications:
  email: false

# Default phases (can be overridden in jobs)
install: npm ci
script:
  - npm run lint
  - npm test

stages:
  - name: test
  - name: publish
    if: tag IS present

jobs:
  include:
    - name: "Test on Linux"
      stage: test
      os: linux
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
    - name: "Test on OSX"
      stage: test
      os: osx
    - name: "Test on Windows"
      stage: test
      os: windows
    - name: "Publish from Linux"
      stage: publish
      os: linux
      script: npm run publish
    - name: "Publish from OSX"
      stage: publish
      os: osx
      script: npm run publish
    - name: "Publish from Windows"
      stage: publish
      os: windows
      script: npm run publish
