language: node_js
os:
  - windows
  - osx
  - linux
node_js:
  - "lts/*"
notifications:
  email: false

before_script:
  if: os = linux
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
