language: node_js
node_js:
  - "lts/*"
notifications:
  email: false

stages:
  - name: lint
  - name: test
  - name: publish
    if: tag IS present

jobs:
  include:
    - name: "Check Linting"
      stage: lint
      os: linux
      script: npm run lint
    - name: "Test on Linux"
      stage: test
      os: linux
      services:
        - xvfb
      before_script:
        - export DISPLAY=:99.0
      script: npm test
    - name: "Test on OSX"
      stage: test
      os: osx
      script: npm test
    - name: "Test on Windows"
      stage: test
      os: windows
      script: npm test
    - name: "Publish from Linux"
      stage: publish
      os: linux
      script: npm run publish
    - name: "Publish from OSX"
      stage: publish
      os: osx
      script: npm run publish
    - name: "Publish from Windows"
      stage: publish
      os: windows
      script: npm run publish
